#obviously not real code; used to indenting
def(output_stacked_in_order_drawn):
    9 of Clubs,
    3 of Spades, 
    4 of Spades, 
    Ace of Clubs, 
    7 of Diamonds, 
    4 of Hearts, 
    4 of Clubs, 
    Ace of Diamonds, 
    5 of Hearts, 
    Queen of Clubs, 
    Jack of Spades, 
    10 of Spades, 
    8 of Clubs, 
    Jack of Clubs, 
    8 of Diamonds, 
    2 of Clubs, 
    10 of Clubs, 
    3 of Hearts, 
    Queen of Hearts, 
    2 of Spades, 
    6 of Diamonds, 
    8 of Hearts, 
    9 of Spades, 
    Queen of Diamonds, 
    3 of Diamonds, 
    5 of Clubs, 
    7 of Hearts, 
    King of Spades, 
    Jack of Diamonds, 
    2 of Diamonds, 
    2 of Clubs, 
    7 of Clubs, 
    2 of Hearts, 
    9 of Hearts, 
    4 of Diamonds, 
    9 of Diamonds, 
    6 of Hearts, 
    Queen of Spades, 
    6 of Spades, 
    5 of Spades, 
    King of Hearts, 
    Ace of Hearts, 
    8 of Spades, 
    King of Clubs, 
    10 of Diamonds, 
    5 of Diamonds, 
    6 of Clubs, 
    3 of Clubs, 
    10 of Hearts, 
    Ace of Spades, 
    Jack of Hearts, 
    7 of Spades


#Program correctly errored after attempting to draw a 53rd card
#value of all cards in deck is apparently 365, though I got 372; 7 higher than normal
#program drew duplicate cards; namely 2 of clubs; this is why!
#Rerun the modified testcode.py (removing the 21 check code), but also print rngroll after each itteration to see what went wrong